server:
  port: 8889

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config

---
spring:
  profiles: 
    active: native
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/